"""Regenerate the publications chart data from the page and the bibliography.

The counts in assets/js/pubs-chart.js used to be typed by hand with a comment
asking whoever edited the list to keep them in sync. They drifted the moment
three publication years were corrected. Section membership now comes from
_pages/publications.md and the year from files/chengyuan-zhang.bib, which is
itself generated from Crossref and the arXiv API, so the chart cannot disagree
with the list above it.

Run from anywhere; pass --check to compare without writing.
"""
from __future__ import annotations

import io
import os
import re
import sys
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

SECTION_KIND = {
    "preprints and manuscripts under review": "preprint",
    "journal publications": "journal",
    "conference publications": "conference",
    "books": "book",
    "patents": "patent",
}
KINDS = ["journal", "conference", "preprint", "book", "patent"]


def repo_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))


def bib_years(path: str) -> Dict[str, str]:
    text = io.open(path, encoding="utf-8").read()
    years: Dict[str, str] = {}
    for block in re.split(r"\n(?=@)", text):
        key = re.match(r"@\w+\{([^,]+),", block)
        year = re.search(r"\n\s*year\s*=\s*\{(\d{4})\}", block)
        if key and year:
            years[key.group(1).strip()] = year.group(1)
    return years


def page_entries(path: str) -> List[Tuple[str, str]]:
    """Return (bib key, section kind) in document order."""
    entries: List[Tuple[str, str]] = []
    kind: Optional[str] = None
    for line in io.open(path, encoding="utf-8"):
        heading = re.match(r"##\s+(.*?)\s*$", line)
        if heading:
            kind = SECTION_KIND.get(heading.group(1).strip().lower())
            continue
        for key in re.findall(r'data-bib="([^"]+)"', line):
            if kind is None:
                raise ValueError("entry %s appears before any section heading" % key)
            entries.append((key, kind))
    return entries


def build(root: str) -> Tuple[List[Dict[str, int]], List[str]]:
    years = bib_years(os.path.join(root, "files", "chengyuan-zhang.bib"))
    entries = page_entries(os.path.join(root, "_pages", "publications.md"))
    counts: Dict[int, Dict[str, int]] = defaultdict(lambda: dict.fromkeys(KINDS, 0))
    warnings: List[str] = []
    for key, kind in entries:
        if key not in years:
            warnings.append("bib 里没有 %s, 已跳过" % key)
            continue
        counts[int(years[key])][kind] += 1
    rows = [dict(year=y, **counts[y]) for y in range(min(counts), max(counts) + 1)]
    return rows, warnings


def render(rows: List[Dict[str, int]], indent: str) -> str:
    lines = []
    for r in rows:
        lines.append(indent + "  { year: %d, journal: %d, conference: %d, preprint: %d, "
                     "book: %d, patent: %d }"
                     % (r["year"], r["journal"], r["conference"], r["preprint"],
                        r["book"], r["patent"]))
    return indent + "var DATA = [\n" + ",\n".join(lines) + "\n" + indent + "];"


def main() -> int:
    root = repo_root()
    rows, warnings = build(root)
    for w in warnings:
        print("  警告:", w)

    total = sum(r[k] for r in rows for k in KINDS)
    print("按 bib 年份与页面分节统计, 共 %d 条, %d-%d" % (total, rows[0]["year"], rows[-1]["year"]))
    for r in rows:
        parts = ", ".join("%s %d" % (k, r[k]) for k in KINDS if r[k])
        print("   %d  %s" % (r["year"], parts))

    path = os.path.join(root, "assets", "js", "pubs-chart.js")
    raw = io.open(path, encoding="utf-8", newline="").read()
    newline = "\r\n" if "\r\n" in raw else "\n"
    text = raw.replace("\r\n", "\n")

    pattern = re.compile(r"^([ \t]*)var DATA = \[.*?\n[ \t]*\];", re.S | re.M)
    if pattern.search(text) is None:
        print("未找到 DATA 数组")
        return 1
    indent = pattern.search(text).group(1)
    updated = pattern.sub(lambda _: render(rows, indent), text, count=1)
    updated = re.sub(
        r"^\s*\*\s*Counts are kept in sync with the list on /publications/\.\s*$",
        "   * DATA is generated by scripts/build_pubs_chart.py from the section\n"
        "   * headings in _pages/publications.md and the years in\n"
        "   * files/chengyuan-zhang.bib. Do not edit it by hand.",
        updated, count=1, flags=re.M)

    if updated == text:
        print("图表数据已是最新")
        return 0
    if "--check" in sys.argv:
        print("图表数据与来源不一致 (--check 模式, 未写入)")
        return 1
    io.open(path, "w", encoding="utf-8", newline="").write(updated.replace("\n", newline))
    print("已更新 assets/js/pubs-chart.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
